In [8]:
import pandas as pd
import re
import pickle

pd.options.display.max_columns = 100

In [9]:
morning = pickle.load(open('jogr112_close_frame','rb')) #close of day before/ morning
afternoon = pickle.load(open('jogr112_intraday_frame','rb')) #intra day

In [10]:
afternoon.head()

,Month,Cash_Bids_1,Cash_Bids_2,Basis1_1,Basis1_2,Contract,Crop,Date
0,Mar,5.4325,5.4825,87,92,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440
1,Apr,5.4125,5.4225,85,86,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440
2,May,5.3925,5.4225,83,86,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440
3,Jun,5.2825,5.3125,65,68,+N,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440
4,Jul,5.2825,5.3125,65,68,+N,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440

In [11]:
merged = pd.merge(afternoon,morning,left_on=afternoon.index, right_on=morning.index, suffixes=('_morning','_afternoon'))
merged = merged.replace('NA',0)

merged = merged.drop(['key_0', 'Change2_1','Change2_2'], axis=1)

In [12]:
merged.head()

,Month_morning,Cash_Bids_1_morning,Cash_Bids_2_morning,Basis1_1_morning,Basis1_2_morning,Contract_morning,Crop_morning,Date_morning,Month_afternoon,Cash_Bids_1_afternoon,Cash_Bids_2_afternoon,Change1_1,Change1_2,Basis1_1_afternoon,Basis1_2_afternoon,Contract_afternoon,Crop_afternoon,Date_afternoon
0,Mar,5.4325,5.4825,87,92,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440,Mar,5.4925,5.5525,up,9.5,87,93,,Louisiana Midday bids and basis for US 2 Soft ...,2019-03-18 02:08:25.156134
1,Apr,5.4125,5.4225,85,86,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440,Apr,5.4725,5.4925,up,9.5,85,87,,Louisiana Midday bids and basis for US 2 Soft ...,2019-03-18 02:08:25.156134
2,May,5.3925,5.4225,83,86,+K,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440,May,5.4525,5.4925,up,9.5,83,87,,Louisiana Midday bids and basis for US 2 Soft ...,2019-03-18 02:08:25.156134
3,Jun,5.2825,5.3125,65,68,+N,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440,Jun,5.3325,5.4025,up,8.5,65,72,,Louisiana Midday bids and basis for US 2 Soft ...,2019-03-18 02:08:25.156134
4,Jul,5.2825,5.3125,65,68,+N,Louisiana Morning bids and basis for US 2 Soft...,2019-03-18 12:42:18.821440,Jul,5.3325,5.4025,up,8.5,65,72,,Louisiana Midday bids and basis for US 2 Soft ...,2019-03-18 02:08:25.156134

In [13]:
# # finds difference between previous close and afternoon
# Cash_Bids_Change1 = merged['Cash_Bids_1_morning'].astype('float') - merged['Cash_Bids_1_afternoon'].astype('float')
# Cash_Bids_Change2 = merged['Cash_Bids_2_morning'].astype('float') - merged['Cash_Bids_2_afternoon'].astype('float')

# Basis_Change1 = merged['Basis1_1_morning'].astype('float') - merged['Basis1_1_afternoon'].astype('float')
# Basis_Change2 =merged['Basis1_2_morning'].astype('float') - merged['Basis1_2_afternoon'].astype('float')

# final = merged[['Month_afternoon', 'Crop_afternoon','Contract_afternoon']]
# final['Cash_Bids_Change1'] = Cash_Bids_Change1
# final['Cash_Bids_Change2'] = Cash_Bids_Change2
# final['Basis_Change1'] = Basis_Change1
# final['Basis_Change2'] = Basis_Change2
# final = final.replace(0,'NA')
# final

# out = pd.DataFrame({
#                     "Month": final['Month_afternoon'],
#                     "Crop": final["Crop_afternoon"],
#                     "Cash_bids_difference1":final['Cash_Bids_Change1'],
#                     "Cash_bids_difference2": final['Cash_Bids_Change2'],
#                     "Basis_difference1": final['Basis_Change1'],
#                     "Basis_difference2": final['Basis_Change2']
#                     })
# out
# out.to_csv('finalframe2.csv')